spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    #    active: prod
    active: dev
#    active: test




#rsa密文传递密码
rsa:
  privateKey: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEArIWDLtkJDLlFN9xkaH59zP8CcGAm5uKnDjz/2VcLtn7mnJU0iBpPM4pucMyNOQ1n2fD04+axG0500UACgKOKlQIDAQABAkEAiM6vQn01YfOhYjTRItP76o3mXzrAXqMpmm7g7HbMgQA/hzx8k+BT17w48pAwfAb5EOVgAVrlPdLdYdXVClhaAQIhANSj+iyDKMu14EsFPrOulpXZgOXSFtG7rKuCSah88v5BAiEAz7NJuZtTxvnEk8vSFpn7w/anFjfqGuUTGKRQCdbbX1UCIQCGhHF4BUUikZ0heGDxJGpIw77CJIShC3uxSAu21cyWwQIgQQxIga2ozj85FoSV9mghVl0wNSAr3GJz2ZrUSlCVAcUCIFwx2mZXtsfv19tNYGHc4SzPJHBGgodOrjv2z4bJF+Em
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKyFgy7ZCQy5RTfcZGh+fcz/AnBgJubipw48/9lXC7Z+5pyVNIgaTzOKbnDMjTkNZ9nw9OPmsRtOdNFAAoCjipUCAwEAAQ==



#白名单
ignore:
  whites:
    - /login
    - /logout
    - /captcha
    - /favicon.ico
    - /webjars/**
    - /img.icons/**
    - /swagger-resources/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /doc.html