server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: zhaojun98

  #邮件服务
  mail:
    host: smtp.163.com
    username: 13698274091@163.com   #发送者邮箱
    password: USTIUSIHQuuKUNJ      #授权密码
    default-encoding: UTF-8

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password: zhaojun98
    #redis数据库索引，默认0
    database: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      table-prefix: sys_
    configuration-properties:
      prefix: sys_ # 自定义sql中表名带前缀
markerhub:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

#swagger文档开启/关闭
swagger:
  apiProfile:
    path: /
#knife4j
knife4j:
  production: false # 开启/屏蔽文档资源